disabled_rules:
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - identifier_name
  - private_over_fileprivate
opt_in_rules:
  - empty_count

included: 
  - Noveo Training
excluded:
  - Carthage
  - Pods
analyzer_rules:
  - explicit_self

force_cast: warning 
force_try:
  severity: warning 
line_length: 100
type_body_length:
  - 300 
  - 400 
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 4 
  max_length: 
    warning: 40
    error: 50
  excluded: iPhone 
  allowed_symbols: ["_"] 
identifier_name:
  min_length: 
    error: 4 
  excluded: 
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"
